variables:
  CI_TARGET_INTEGRATE_REPO: "http://gitlab.internal.sensorsdata.cn/front-end/sensors-analytics-app.git" # 需要集成测试的父应用
  CI_TARGET_INTEGRATE_BRANCH: "release/1.17.0" # 需要集成测试的父应用的分支
  CI_PROJECT_NAME_CN: "你的模块中文名" # 微信推送使用
  CI__TARGET_INTEGRATE_OUTPUT_DIRNAME: "new" # 父应用 运行 npm run build 产生的文件夹名称（主要是 SA 需要改名 new 才能直接部署，其他项目一般写 dist）

stages:
  - build_with_sa
  # - deploy_to_debug # 需要部署请删掉注释
  - publish_to_npm

# 集成测试编译 (由 PR 和 打 tag 触发)
build_with_sa:
  stage: build_with_sa
  only:
    - tags
    - merge_requests
  script:
    - /bin/bash ./scripts/build_with_sa.sh
  artifacts:
    expire_in: 7 day
    name: "$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - new/ # 请和 CI__TARGET_INTEGRATE_OUTPUT_DIRNAME 保持一致 例如写 dist/

# 集成测试部署到测试机 需要部署请删掉注释
# deploy_to_debug:
#   stage: deploy_to_debug
#   only:
#     - merge_requests
#   script:
#     - /bin/bash ./scripts/deploy_to_debug.sh
#   dependencies:
#     - build_with_sa

# 人工确认发布到npm
publish_to_npm:
  stage: publish_to_npm
  only:
    - tags
  when: manual
  script:
    - /bin/bash ./scripts/publish_to_npm.sh
  dependencies: []